### ISSUE TITLE
传递消息【树形DP】 

### ISSUE THREAD

**Issue by cjhyy** [cjhyy/-NOIP-#1]
3.消息传递

【问题描述】

巴蜀国的社会等级森严，除了国王之外，每个人均有且只有一个直接上级，当然国王没有上级。如果A是B的上级，B是C的上级，那么A就是C的上级。绝对不会出现这样的关系：A是B的上级，B也是A的上级。

　　最开始的时刻是0，你要做的就是用1单位的时间把一个消息告诉某一个人，让他们自行散布消息。在任意一个时间单位中，任何一个已经接到消息的人，都可以把消息告诉他的一个直接上级或者直接下属。

现在，你想知道：

1.到底需要多长时间，消息才能传遍整个巴蜀国的所有人？

2.要使消息在传递过程中消耗的时间最短，可供选择的人有那些？

【文件输入】

输入文件的第一行为一个整数N（N≤1000），表示巴蜀国人的总数，假如人按照1到n编上了号码，国王的编号是1。第2行到第N行（共N-1行），每一行一个整数，第i行的整数表示编号为i的人直接上级的编号。

【文件输出】

文件输出共计两行：

第一行为一个整数，表示最后一个人接到消息的最早时间。

第二行有若干个数，表示可供选择人的编号，按照编号从小到大的顺序输出，中间用空格分开。

【样例输入】

8

1

1

3

4

4

4

3

【样例输出】

5

3 4 5 6 7

 

解题报告：

思路：最开始没想到是树形DP-想到了也不会做；

经验：细心。。我快拍错了一个>符号，调了3个小时；

**Comment by cjhyy** [comment]
type
  pnode=^tnode;
  tnode=record
     dian:longint;
     next:pnode;
end;
var
  first:array[-1000..30001]  of pnode;
  q:array[0..1000,0..1000]  of longint;
  r,f:array[0..1000]of longint;
  visit:array[0..30001]  of boolean;
  ok:array[0..1000] of longint;
  n,m,z,max,min:longint;
procedure init;
begin
  assign(input,'news.in');
  assign(output,'news.out');
  reset(input);
  rewrite(output);
end;
procedure terminal;
begin
  close(input);
  close(output);
  halt;
end;
procedure insert(x,y:longint);
var p:pnode;
begin
  new(p);
  p^.dian:=y;
  p^.next:=first[x];
  first[x]:=p;
end;
procedure qsort(l,r,x:longint);     //升序排列
var
  i,j,mid,t:longint;
begin
  i:=l; j:=r; mid:=q[x,(i+j) shr 1];
  repeat
    while q[x,i]>mid do inc(i);//大于符号
    while q[x,j]<mid do dec(j);//小于符号
    if i<=j then
    begin
      t:=q[x][i]; q[x][i]:=q[x][j]; q[x][j]:=t;
      inc(i); dec(j);
    end;
  until i>j;
  if j>l then qsort(l,j,x);
  if i<r then qsort(i,r,x);
end;
procedure dfs(v:longint);
var
  p:pnode;
  i:longint;
begin
  f[v]:=0; r[v]:=0;
  visit[v]:=true;
  p:=first[v];
  while p<>nil do
  begin
    if not visit[p^.dian] then
    begin
      dfs(p^.dian);
      inc(r[v]);
      q[v,r[v]]:=f[p^.dian];
    end;
    p:=p^.next;
  end;
  qsort(1,r[v],v);
  for i:=1 to r[v] do
  if f[v]<q[v,i]+i then f[v]:=q[v,i]+i;
  if f[v]=0 then f[v]:=1;
  end;
procedure main;
var i,x:longint;
begin
  min:=maxlongint;
  readln(n);
  for i:=1 to n-1 do
  begin
    readln(x);
    begin
    insert(x,i+1);
    insert(i+1,x);
    end;
  end;
  min:=maxlongint;
  x:=0;
  fillchar(q,sizeof(q),0);
  for i:=1 to n do
  begin
  fillchar(visit,sizeof(visit),false);
  dfs(i);
  if f[i]=min then begin inc(x); ok[x]:=i; end;
  if f[i]<min then
  begin
    x:=1;
    min:=f[i];
    fillchar(ok,sizeof(ok),0);
    ok[1]:=i;
  end;
  end;
  writeln(min);
  for i:=1 to x do
  write(ok[i],' ');
end;
begin
  init;
  main;
  terminal;
end.

**Comment by Shuumatsu** [comment]
你搬的是个锤子 markdown写起来格式弄上去啊
